import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import Image from 'next/image'
import NavBar from '@/components/custom/nav-bar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="block shadow-lg">
            <div className="container mx-auto">
              <div className="flex items-center justify-between p-4 gap-4 h-16">
                <Link href="/">
                  <Image src="/images/logo-icon.png" width={50} height={50} alt="logo" />
                </Link>
                <NavBar />
                <div className="space-x-2">
                  <SignedOut>
                    <SignInButton>
                      <Button className="bg-primary ">
                        <Link href="/sign-in" className="text-gray-900">
                          Sign in
                        </Link>
                      </Button>
                    </SignInButton>
                    <SignUpButton>
                      <Link href="/sign-up" className="text-black text-sm">
                        Sign up
                      </Link>
                    </SignUpButton>
                  </SignedOut>
                  <SignedIn>
                    <UserButton />
                  </SignedIn>
                </div>
              </div>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
